# Generated by Django 4.1.4 on 2022-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip_fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
